FROM maven:3.3-jdk-8 as builder
RUN git clone "YOUR_MAVEN_PROJECT_GIT_REPO"
WORKDIR /var/
RUN mvn clean install

FROM java:8-jre
ADD 'http://ftp.byfly.by/pub/apache.org/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.zip' .
RUN apt-get install unzip && unzip apache-tomcat-8.5.32.zip && chmod -R +x /apache-tomcat-8.5.32
COPY --from=builder /p323line/helloworld-ws/target/helloworld-ws.war /apache-tomcat-8.5.32/webapps/
ENTRYPOINT ["/apache-tomcat-8.5.32/bin/catalina.sh"]
CMD ["run"]
EXPOSE 8080
